/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Entrada.java
 *
 * Created on 11-nov-2009, 19:36:16
 */

package poker;



import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Color;
import java.net.URL;
import org.jdesktop.application.Action;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class Entrada extends javax.swing.JFrame {

    public String p,s,j,total,nombrefichero;
    int rotacion=0;
    private URL nombre;
    private AudioClip sonido;

    /** Creates new form Entrada */
    public Entrada() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        Imagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        EmpezarPartida = new javax.swing.JButton();
        NickName = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem SalirMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu InformacionMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem Creadores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(poker.PokerApp.class).getContext().getResourceMap(Entrada.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Panel.setName("Panel"); // NOI18N

        Imagen.setIcon(resourceMap.getIcon("Imagen.icon")); // NOI18N
        Imagen.setText(resourceMap.getString("Imagen.text")); // NOI18N
        Imagen.setName("Imagen"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        EmpezarPartida.setText(resourceMap.getString("EmpezarPartida.text")); // NOI18N
        EmpezarPartida.setName("EmpezarPartida"); // NOI18N
        EmpezarPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpezarPartidaMouseClicked(evt);
            }
        });

        NickName.setText(resourceMap.getString("NickName.text")); // NOI18N
        NickName.setName("NickName"); // NOI18N

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NickName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmpezarPartida)))
                        .addGap(44, 44, 44))))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Imagen, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NickName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(EmpezarPartida)
                .addGap(32, 32, 32))
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setLabel(resourceMap.getString("fileMenu.label")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(poker.PokerApp.class).getContext().getActionMap(Entrada.class, this);
        SalirMenuItem.setAction(actionMap.get("quit")); // NOI18N
        SalirMenuItem.setLabel(resourceMap.getString("SalirMenuItem.label")); // NOI18N
        SalirMenuItem.setName("SalirMenuItem"); // NOI18N
        fileMenu.add(SalirMenuItem);

        menuBar.add(fileMenu);

        InformacionMenu.setText(resourceMap.getString("InformacionMenu.text")); // NOI18N
        InformacionMenu.setName("InformacionMenu"); // NOI18N

        Creadores.setAction(actionMap.get("showAboutBox")); // NOI18N
        Creadores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        Creadores.setLabel(resourceMap.getString("Creadores.label")); // NOI18N
        Creadores.setName("Creadores"); // NOI18N
        InformacionMenu.add(Creadores);

        menuBar.add(InformacionMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       int value=JOptionPane.showConfirmDialog(null,"¿Esta seguro de que quiere salir sin guardar?","Aviso", JOptionPane.OK_CANCEL_OPTION);
       if (value==JOptionPane.OK_OPTION){
       System.exit(0);} // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void EmpezarPartidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpezarPartidaMouseClicked
       nombrefichero="No.wav";
       Sonar(nombrefichero);        // TODO add your handling code here:
       String nick = NickName.getText();
       System.out.println("El usuario es: "+nick);
       if(nick.compareTo("")==0 ){
           nombrefichero="No.wav";
           Sonar(nombrefichero);        // TODO add your handling code here:
           jLabel1.setForeground(Color.red);
           jLabel1.setText("Nick incorrecto");
       }
       else{
       Prueba p = new Prueba(nick);
       p.setVisible(true);
       this.setVisible(false);
       }
    }//GEN-LAST:event_EmpezarPartidaMouseClicked

    /**
    * @param args the command line arguments
    */
  
     @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = PokerApp.getApplication().getMainFrame();
            aboutBox = new PokerAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);

        }
        PokerApp.getApplication().show(aboutBox);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EmpezarPartida;
    private javax.swing.JLabel Imagen;
    private javax.swing.JTextField NickName;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

    private JDialog aboutBox;




public void Sonar(String nombrefichero){
     try {
            nombre= new URL("file:./sonido/" +nombrefichero);
        } catch (Exception ex) {
            System.out.println("Excepcion: ");
            ex.printStackTrace();
        }

        sonido=Applet.newAudioClip(nombre);
        //sonido.play();

    }






}
